#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
set -eu
LC_ALL=C
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: debe ser root\e[00m"
	exit 1
fi
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid

name=$(hostname)
mkdir -p /tmp/"$name"
chmod 666 /tmp/"$name"

lscpu > /tmp/"$name"/cpu.txt
lspci > /tmp/"$name"/pci.txt
lspcmcia  > /tmp/"$name"/pcmcia.txt
lsusb > /tmp/"$name"/usb.txt
hwinfo -all --listmd --log /tmp/"$name"/hwinfo.log

echo -e "\e[00;1;92mFinalizado...\e[00m"
rm -f /run/$(basename $0).pid
exit 0
